#pragma once
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cassert>
#include "complex.h"
#include "Seq.h"
#include "LinkedList.h"
#include "DynamicArray.h"
#include "ListSequence.h"
#include "ArraySequence.h"
#include "Polynom.h"
#include "LiniarForm.h"
void Menu();
void Randomvalues();
void Main_menu();
void Menu_Lin();
void Randomvalues_Lin();
void Grand_Menu();